# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: 'Release'
on: 'push'
jobs:
  release:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Create a Release'
        uses: 'softprops/action-gh-release@v2'
        if: "startsWith(github.ref, 'refs/tags/')"
        with:
          prerelease: true
          generate_release_notes: true
